services:
    database:
        image: mysql:latest
        expose:
            - 3306
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_HOST=%
        volumes:
            - database_data:/var/lib/mysql
volumes:
    database_data:

